Release v4.2
seisman/SAC_Docs_zh pull request #246
Opened 2021-06-11 13:00 UTC by core-man

Fixes #244.﻿

2021-06-11 13:03 UTC, core-man commented on source/appendix/changelog.rst
> +维护
我使用了字标题，之前一直使用nested list

2021-06-11 13:03 UTC, core-man commented on source/appendix/changelog.rst
> +- 修复 typos
我建议修复 typos 不用列出来了，no？

2021-06-11 13:03 UTC, core-man commented on source/appendix/changelog.rst
> +=================
以下更新的commit是按照时间从早到晚排列的

2021-06-11 13:04 UTC, core-man commented
本地编译警告：

```
/SAC_Docs_zh/source/commands/plotpk.rst:48: WARNING: undefined label: table:plotpk-commands
/SAC_Docs_zh/source/commands/plotpk.rst:61: WARNING: undefined label: table:plotpk-commands
/SAC_Docs_zh/source/commands/readcss.rst:92: WARNING: Failed to create a cross reference. A title or caption not found: table:bandcode
/SAC_Docs_zh/source/commands/taper.rst:48: WARNING: undefined label: table:taper-functions
/SAC_Docs_zh/source/data-process/picking-phase.rst:155: WARNING: undefined label: table:plotpk-commands
/SAC_Docs_zh/source/data-process/picking-phase.rst:230: WARNING: undefined label: table:plotpk-commands
```

2021-06-11 13:44 UTC, seisman commented on source/appendix/changelog.rst
> +- 修复 typos
不需要列

2021-06-11 13:44 UTC, seisman commented on source/appendix/changelog.rst
> +- 所有 code-block: bash 指令替换为 code-block: console
关于维护方面其实也没必要写

2021-06-11 13:44 UTC, seisman commented on source/version.rst
> +   4.2        2021-06-12     102.0     2020-09-01
v4.2 依然是基于 SAC 101.6a 的。
```suggestion
   4.2        2021-06-12     101.6a     2013-11-11
```

2021-06-11 13:51 UTC, seisman commented
> 本地编译警告：
> 
> ```
> /SAC_Docs_zh/source/commands/plotpk.rst:48: WARNING: undefined label: table:plotpk-commands
> /SAC_Docs_zh/source/commands/plotpk.rst:61: WARNING: undefined label: table:plotpk-commands
> /SAC_Docs_zh/source/commands/readcss.rst:92: WARNING: Failed to create a cross reference. A title or caption not found: table:bandcode
> /SAC_Docs_zh/source/commands/taper.rst:48: WARNING: undefined label: table:taper-functions
> /SAC_Docs_zh/source/data-process/picking-phase.rst:155: WARNING: undefined label: table:plotpk-commands
> /SAC_Docs_zh/source/data-process/picking-phase.rst:230: WARNING: undefined label: table:plotpk-commands
> ```
> 
> 以 `plotpk` 为例
> 
> Vercel 预览可以通过：[sac-docs-zh-bij2vjvzk-seisman.vercel.app/commands/plotpk](https://sac-docs-zh-bij2vjvzk-seisman.vercel.app/commands/plotpk/)
> 
> ![2](https://user-images.githubusercontent.com/50591376/121691178-48ae9300-caf9-11eb-894d-35e41b567f73.png)
> 
> 本地有问题：
> ![1](https://user-images.githubusercontent.com/50591376/121691171-46e4cf80-caf9-11eb-8300-39f7ccaab58b.png)

我比较怀疑是 sphinx 4.x 的 bug 或不兼容更新。

2021-06-11 13:56 UTC, core-man commented
我本地确实是4.0.2

2021-06-11 13:56 UTC, core-man commented on source/appendix/changelog.rst
> +- 所有 code-block: bash 指令替换为 code-block: console
removed?

2021-06-11 13:56 UTC, core-man commented on source/appendix/changelog.rst
> +- 修复 typos
```suggestion
```

2021-06-11 14:01 UTC, seisman commented on source/appendix/changelog.rst
> +- 所有 code-block: bash 指令替换为 code-block: console
我觉得可以删掉

2021-06-11 14:05 UTC, core-man commented on source/appendix/changelog.rst
> +- 所有 code-block: bash 指令替换为 code-block: console
```suggestion
```

2021-06-11 14:05 UTC, core-man commented on source/appendix/changelog.rst
> +
```suggestion
```

2021-06-11 14:13 UTC, seisman commented on source/appendix/changelog.rst
> +- 新建”SAC 安装“一章，包含“申请 SAC“和 不同系统下的 SAC 安装
```suggestion

- 新建“SAC 安装”一章，包含“申请 SAC”和不同系统下的 SAC 安装
```

2021-06-11 14:13 UTC, seisman submitted a review, later dismissed

2021-06-11 14:20 UTC, core-man commented
明天再merge，顺便发布 release？ 源码和pdf还有必要传吗？

2021-06-11 14:23 UTC, seisman commented
> 明天再merge，顺便发布 release？ 

看你时间安排，哪天发布无所谓。

> 源码和pdf还有必要传吗？如果传可以参考 [gmt-china/china-geospatial-data#18](https://github.com/gmt-china/china-geospatial-data/pull/18)

PDF 需要上传。

2021-06-11 14:24 UTC, seisman commented
PDF 上传，手动即可。SAC 手册发布不频繁，没必要新建一个 workflow，增加工作量也增加维护量

2021-06-12 03:43 UTC, wangliang1989 requested changes

2021-06-12 03:43 UTC, wangliang1989 commented on source/version.rst
> +   4.2        2021-06-12     101.6a     2013-11-11
```suggestion
   4.2        2021-06-12     101.6a    2013-11-11
```

2021-06-12 03:52 UTC, wangliang1989 commented on source/SAC_style.sty
>  \newcommand{\SACDOCDATE}{\today}                  % 文档发布日期
发布日期是否可以考虑改称为为固定。然后增加一个编译日期是\today

2021-06-12 04:01 UTC, seisman commented on source/SAC_style.sty
>  \newcommand{\SACDOCDATE}{\today}                  % 文档发布日期
> 发布日期是否可以考虑改称为为固定。然后增加一个编译日期是\today

这么做的目的是?

2021-06-12 06:33 UTC, wangliang1989 commented on source/SAC_style.sty
>  \newcommand{\SACDOCDATE}{\today}                  % 文档发布日期
本来二者就不同

2021-06-12 10:36 UTC, core-man commented on source/SAC_style.sty
>  \newcommand{\SACDOCDATE}{\today}                  % 文档发布日期
发布和编译不是同一天吗？

2021-06-12 10:42 UTC, core-man commented
@seisman @wangliang1989 准备今晚9点merge~

2021-06-12 10:55 UTC, wangliang1989 commented on source/SAC_style.sty
>  \newcommand{\SACDOCDATE}{\today}                  % 文档发布日期
> 发布和编译不是同一天吗？[deploy.yml](https://github.com/seisman/SAC_Docs_zh/blob/master/.github/workflows/deploy.yml) 自动编译HTML和PDF，所以编译之日即发布之日，no？

编译可以是任何一个分支，任何一个commit后的编译，然而发布是我们的一个官方的行为

2021-06-12 11:42 UTC, core-man commented on source/SAC_style.sty
>  \newcommand{\SACDOCDATE}{\today}                  % 文档发布日期
每次commit后都会编译和发布 PDF，即 https://seisman.github.io/SAC_Docs_zh/SAC_Docs.pdf 。每个 release 的发布也是如此，只不过是一个特定的commit。

2021-06-12 11:45 UTC, core-man commented on source/SAC_style.sty
>  \newcommand{\SACDOCDATE}{\today}                  % 文档发布日期
目前的流程，编译和发布日期永远会是相同的话，设置两个略显累赘，no？

2021-06-12 11:58 UTC, wangliang1989 commented on source/SAC_style.sty
>  \newcommand{\SACDOCDATE}{\today}                  % 文档发布日期
那就算了吧

2021-06-12 11:58 UTC, wangliang1989 approved these changes

2021-06-12 14:37 UTC, merged